# Framework configuration to enable stateless CSRF protection.
framework:
    form:
        csrf_protection:
            token_id: submit  # Declares a CSRF token identifier for forms (e.g., "submit").

    csrf_protection:
        # List of CSRF token identifiers used in stateless contexts.
        stateless_token_ids:
            - submit         # CSRF token for form submissions.
            - authenticate   # CSRF token used for authentication processes.
            - logout         # CSRF token to secure logout actions.

    # CSRF protection is a security measure that prevents malicious requests
    # from being made by third parties on behalf of a legitimate user.
    # This file configures that protection in a framework (Symfony).

    # The "form" key and its "csrf_protection" sub-element:
    # Defines a specific CSRF token to secure forms.
    # The option token_id: submit assigns an identifier to this token.

    # The "csrf_protection" key and its stateless tokens:
    # The identifiers listed in "stateless_token_ids" are used in scenarios
    # where no persistent session is present (such as REST APIs).
    # Each critical action (like submit, authenticate, or logout) is protected by a dedicated token.