doctrine:
    dbal:
        # Database connection URL, configured via an environment variable.
        # The '%env(resolve:DATABASE_URL)%' prefix allows dynamic resolution of the URL.
        url: '%env(resolve:DATABASE_URL)%'

        # Enables collection of profiling traces to debug SQL queries.
        profiling_collect_backtrace: '%kernel.debug%'

        # Enables the use of savepoints to allow partial rollbacks in nested transactions.
        use_savepoints: true

    orm:
        auto_generate_proxy_classes: true

        # Enables lazy ghost objects for better relationship management.
        enable_lazy_ghost_objects: true
        # Reports fields in the entity where they are declared, useful for debugging.
        report_fields_where_declared: true
        # Validates the XML mapping of entities to prevent configuration errors.
        validate_xml_mapping: true

        # Uses a naming strategy that converts names to underscore format (e.g., `camelCase` → `snake_case`).
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware

        # Defines preferences for identity generation in specific database platforms.
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity

        # Enables automatic mapping of entities to avoid explicit configuration.
        auto_mapping: true

        # Declares the mappings for the `App` namespace.
        mappings:
            App:
                type: attribute               # Uses PHP attributes (modern annotations).
                is_bundle: false              # Indicates this is not a Symfony bundle.
                dir: '%kernel.project_dir%/src/Entity'  # Directory containing entity classes.
                prefix: 'App\Entity'          # Default namespace for entities.
                alias: App                    # Alias used in DQL queries.

        # Controller resolution (advanced option).
        controller_resolver:
            auto_mapping: false  # Disables automatic mapping for controllers.

# Specific configuration for the test environment.
when@test:
    doctrine:
        dbal:
            # Adds a `_test` suffix to the database name to avoid modifying the production database.
            # The "TEST_TOKEN" is often used by ParaTest to differentiate parallel test instances.
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

# Specific configuration for the production environment.
when@prod:
    doctrine:
        orm:
            # Disables automatic proxy class generation to improve performance.
            auto_generate_proxy_classes: false

            # Directory where proxy classes are stored in production.
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'

            # Configures query caching for optimal performance.
            query_cache_driver:
                type: pool  # Uses a cache pool defined in `framework.cache.pools`.
                pool: doctrine.system_cache_pool

            # Configures result caching to improve efficiency of repeated queries.
            result_cache_driver:
                type: pool  # Also uses a cache pool.
                pool: doctrine.result_cache_pool

    framework:
        cache:
            # Declares cache pools for Doctrine.
            pools:
                doctrine.result_cache_pool:    # Cache pool for query results.
                    adapter: cache.app         # Uses the application cache adapter.
                doctrine.system_cache_pool:    # Cache pool for system metadata.
                    adapter: cache.system      # Uses the system cache adapter.
