framework:
    # Defines the application secret.
    secret: '%env(APP_SECRET)%'

    # Session configuration
    session:
        enabled: true
        handler_id: null
        cookie_secure: auto
        cookie_httponly: true
        cookie_samesite: 'lax'
        gc_maxlifetime: 3600  # 20 minutes.
        cookie_lifetime: 3600  # 20 minutes.
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        metadata_update_threshold: 0  # Metadata updated on every request.

    validation:
        auto_mapping:
            App\Entity\: []  # Enables automatic validation for entities.

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
