framework:
    # Définition du secret de l'application.
    secret: '%env(APP_SECRET)%'

    # Configuration de la session
    session:
        enabled: true
        handler_id: null
        cookie_secure: auto
        cookie_httponly: true
        cookie_samesite: 'lax'
        gc_maxlifetime: 3600  # 20 minutes.
        cookie_lifetime: 3600  # 20 minutes.
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        metadata_update_threshold: 0  # Mise à jour des métadonnées à chaque requête

    # Activer la validation (annotations activées automatiquement si doctrine/annotations est installé)
    validation:
        auto_mapping:
            App\Entity\: [] # Active la validation automatique pour les entités

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
