framework:
    mailer:
        # Defines the DSN (Data Source Name) for the mailer service.
        # The DSN is a string containing the necessary information to connect to the mail server.
        dsn: '%env(MAILER_DSN)%'
