framework:
    router:
    # Defines how URLs are generated in non-HTTP contexts (e.g., CLI commands).
    # This is useful for generating valid links even when there is no active HTTP request.

when@prod:
    framework:
        router:
        # In production, `strict_requirements` can be set to `null` to disable strict URL parameter checks.
        # This helps avoid exceptions when required parameters are missing or incorrect.
        # - true : Enables strict checks (throws an exception if there's an issue).
        # - false : Disables strict checks (incorrect URLs won't be generated).
        # - null : Flexible behavior, avoids exceptions while logging errors.
