security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_admin_provider:
            entity:
                class: App\Entity\Admin
                property: email

    firewalls:
        # No security applied to dev assets (profiler, CSS, JS, etc.)
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Firewall for the entire admin area
        admin:
            lazy: true
            provider: app_admin_provider

            form_login:
                login_path: admin_login               # Route to the login form
                check_path: admin_login               # Route where credentials are submitted
                default_target_path: app_admin_dashboard  # Redirect after login
                username_parameter: email
                password_parameter: password

            logout:
                path: admin_logout
                target: admin_login

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800   # 7 days
                path: /

    access_control:
        # Allow public access to the login page
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }

        # ✅ Allow public access to the "Forgot password" page
        - { path: ^/admin/forgot-password, roles: PUBLIC_ACCESS }

        # ✅ Allow public access to the "Reset password" page
        - { path: ^/admin/reset-password, roles: PUBLIC_ACCESS }

        # Everything else under /admin requires ROLE_ADMIN
        - { path: ^/admin, roles: ROLE_ADMIN }
