framework:
    validation:
    # Enables support for auto-mapping of validation constraints.
    # When this option is enabled, Symfony can automatically infer validation constraints
    # from metadata (e.g., annotations or Doctrine configuration).
    #auto_mapping:
    #    App\Entity\: []  # Enables auto-mapping for all entities in the App\Entity namespace.

when@test:
    framework:
        validation:
            # Disables the check for compromised passwords in the test environment.
            # This means the `NotCompromisedPassword` constraint will not be applied during tests.
            # Useful to speed up tests or avoid unnecessary network requests to third-party services
            # such as haveibeenpwned.com.
            not_compromised_password: false
