when@dev:
    web_profiler:
        # Enables the debug toolbar in the development environment.
        # This toolbar appears at the bottom of each page and provides useful information,
        # such as logs, SQL queries, execution time, memory usage, etc.
        toolbar: false

        # Disables automatic interception of HTTP redirects.
        # If set to `true`, Symfony intercepts redirects to display an intermediate page,
        # which helps with debugging redirections.
        intercept_redirects: false

    framework:
        profiler:
            # Collects data for all requests, including successful ones.
            # When set to `true`, the profiler collects data even if no error occurred,
            # which is useful for analyzing performance and request behavior.
            only_exceptions: false

            # Enables data collection related to the serializer.
            # This helps debug serialization or deserialization operations,
            # especially when working with objects or JSON/XML data.
            collect_serializer_data: true

when@test:
    web_profiler:
        # Disables the debug toolbar in the test environment.
        # This avoids rendering the toolbar unnecessarily and reduces resource usage,
        # thereby speeding up automated tests.
        toolbar: false

        # Also disables redirect interception in the test environment.
        # Redirects occur normally, which is essential to ensure
        # tests are not affected by unnecessary debugging features.
        intercept_redirects: false

    framework:
        profiler:
            # Completely disables profiler data collection in the test environment.
            # This reduces memory usage and improves test performance.
            collect: false
