_security_logout:
    # Declares the resource associated with the logout route.
    # This resource refers to a service that loads the logout route configuration.
    # The value 'security.route_loader.logout' refers to an internal Symfony service that handles the logout route.
    resource: security.route_loader.logout

    # Specifies that this resource is a Symfony service and not a standard configuration file (like .yaml or .xml).
    # This allows the logout route to be loaded dynamically through a specific service, in this case `security.route_loader.logout`.
    type: service
