<?php

namespace ContainerBNBur28;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuivisControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hU4fyru.App\Controller\SuivisController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hU4fyru.App\\Controller\\SuivisController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'suivisRepository' => ['privates', 'App\\Repository\\SuivisRepository', 'getSuivisRepositoryService', true],
        ], [
            'suivisRepository' => 'App\\Repository\\SuivisRepository',
        ]))->withContext('App\\Controller\\SuivisController::index()', $container);
    }
}
