parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads'
    uploads_presentation_dir: '%kernel.project_dir%/public/uploads/presentations'
    uploads_suivis_dir: '%kernel.project_dir%/public/uploads/suivis'


services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
