# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:


services:
    # Configuration par défaut pour les services dans *ce* fichier
    _defaults:
        autowire: true      # Autowire permet à Symfony d'injecter automatiquement les dépendances dans les services.
        autoconfigure: true # Autoconfigure permet à Symfony de configurer automatiquement vos services en tant que commandes, abonnés aux événements, etc.

    # Fait en sorte que toutes les classes dans le répertoire src/ soient disponibles comme services
    # Cela crée un service par classe dont l'ID est le nom complet de la classe
    App\:
        resource: '../src/'   # Indique à Symfony où chercher les classes à utiliser comme services (toutes les classes dans le répertoire src/)
        exclude:              # Cette option permet d'exclure certains répertoires de la configuration des services.
            - '../src/DependencyInjection/'  # Exclut le répertoire DependencyInjection
            - '../src/Entity/'               # Exclut le répertoire Entity (il contient des entités de base de données, qui n'ont généralement pas besoin d'être des services)
            - '../src/Kernel.php'            # Exclut le fichier Kernel, car il ne doit pas être traité comme un service

