<?php

namespace ContainerGIuRKW9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U6YV0l5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.U6YV0l5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.U6YV0l5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\AdminDashboardController::index' => ['privates', '.service_locator.egipcEH.App\\Controller\\Admin\\AdminDashboardController::index()', 'getAdminDashboardControllerindexService', true],
            'App\\Controller\\Admin\\AdminDashboardController::createEntity' => ['privates', '.service_locator.mqZqLk1.App\\Controller\\Admin\\AdminDashboardController::createEntity()', 'getAdminDashboardControllercreateEntityService', true],
            'App\\Controller\\Admin\\AdminDashboardController::showEntity' => ['privates', '.service_locator.egipcEH.App\\Controller\\Admin\\AdminDashboardController::showEntity()', 'getAdminDashboardControllershowEntityService', true],
            'App\\Controller\\Admin\\AdminDashboardController::editEntity' => ['privates', '.service_locator.mqZqLk1.App\\Controller\\Admin\\AdminDashboardController::editEntity()', 'getAdminDashboardControllereditEntityService', true],
            'App\\Controller\\Admin\\AdminDashboardController::deleteEntity' => ['privates', '.service_locator.egipcEH.App\\Controller\\Admin\\AdminDashboardController::deleteEntity()', 'getAdminDashboardControllerdeleteEntityService', true],
            'App\\Controller\\Admin\\AdminLoginController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\Admin\\AdminLoginController::login()', 'getAdminLoginControllerloginService', true],
            'App\\Controller\\ContactController::index' => ['privates', '.service_locator.HrQxEjs.App\\Controller\\ContactController::index()', 'getContactControllerindexService', true],
            'App\\Controller\\PresentationController::index' => ['privates', '.service_locator.egipcEH.App\\Controller\\PresentationController::index()', 'getPresentationControllerindexService', true],
            'App\\Controller\\SuivisController::index' => ['privates', '.service_locator.hU4fyru.App\\Controller\\SuivisController::index()', 'getSuivisControllerindexService', true],
            'App\\Controller\\TemoignagesController::index' => ['privates', '.service_locator..8ErHJI.App\\Controller\\TemoignagesController::index()', 'getTemoignagesControllerindexService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\AdminDashboardController:index' => ['privates', '.service_locator.egipcEH.App\\Controller\\Admin\\AdminDashboardController::index()', 'getAdminDashboardControllerindexService', true],
            'App\\Controller\\Admin\\AdminDashboardController:createEntity' => ['privates', '.service_locator.mqZqLk1.App\\Controller\\Admin\\AdminDashboardController::createEntity()', 'getAdminDashboardControllercreateEntityService', true],
            'App\\Controller\\Admin\\AdminDashboardController:showEntity' => ['privates', '.service_locator.egipcEH.App\\Controller\\Admin\\AdminDashboardController::showEntity()', 'getAdminDashboardControllershowEntityService', true],
            'App\\Controller\\Admin\\AdminDashboardController:editEntity' => ['privates', '.service_locator.mqZqLk1.App\\Controller\\Admin\\AdminDashboardController::editEntity()', 'getAdminDashboardControllereditEntityService', true],
            'App\\Controller\\Admin\\AdminDashboardController:deleteEntity' => ['privates', '.service_locator.egipcEH.App\\Controller\\Admin\\AdminDashboardController::deleteEntity()', 'getAdminDashboardControllerdeleteEntityService', true],
            'App\\Controller\\Admin\\AdminLoginController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\Admin\\AdminLoginController::login()', 'getAdminLoginControllerloginService', true],
            'App\\Controller\\ContactController:index' => ['privates', '.service_locator.HrQxEjs.App\\Controller\\ContactController::index()', 'getContactControllerindexService', true],
            'App\\Controller\\PresentationController:index' => ['privates', '.service_locator.egipcEH.App\\Controller\\PresentationController::index()', 'getPresentationControllerindexService', true],
            'App\\Controller\\SuivisController:index' => ['privates', '.service_locator.hU4fyru.App\\Controller\\SuivisController::index()', 'getSuivisControllerindexService', true],
            'App\\Controller\\TemoignagesController:index' => ['privates', '.service_locator..8ErHJI.App\\Controller\\TemoignagesController::index()', 'getTemoignagesControllerindexService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\Admin\\AdminDashboardController::index' => '?',
            'App\\Controller\\Admin\\AdminDashboardController::createEntity' => '?',
            'App\\Controller\\Admin\\AdminDashboardController::showEntity' => '?',
            'App\\Controller\\Admin\\AdminDashboardController::editEntity' => '?',
            'App\\Controller\\Admin\\AdminDashboardController::deleteEntity' => '?',
            'App\\Controller\\Admin\\AdminLoginController::login' => '?',
            'App\\Controller\\ContactController::index' => '?',
            'App\\Controller\\PresentationController::index' => '?',
            'App\\Controller\\SuivisController::index' => '?',
            'App\\Controller\\TemoignagesController::index' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\Admin\\AdminDashboardController:index' => '?',
            'App\\Controller\\Admin\\AdminDashboardController:createEntity' => '?',
            'App\\Controller\\Admin\\AdminDashboardController:showEntity' => '?',
            'App\\Controller\\Admin\\AdminDashboardController:editEntity' => '?',
            'App\\Controller\\Admin\\AdminDashboardController:deleteEntity' => '?',
            'App\\Controller\\Admin\\AdminLoginController:login' => '?',
            'App\\Controller\\ContactController:index' => '?',
            'App\\Controller\\PresentationController:index' => '?',
            'App\\Controller\\SuivisController:index' => '?',
            'App\\Controller\\TemoignagesController:index' => '?',
        ]);
    }
}
