<?php

namespace ContainerMpbW5xM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDebug_Security_Authenticator_RememberMe_AdminService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'debug.security.authenticator.remember_me.admin' shared service.
     *
     * @return \Symfony\Component\Security\Http\Authenticator\Debug\TraceableAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/AuthenticatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/InteractiveAuthenticatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/EntryPoint/AuthenticationEntryPointInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/Debug/TraceableAuthenticator.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/RememberMeAuthenticator.php';

        return $container->privates['debug.security.authenticator.remember_me.admin'] = new \Symfony\Component\Security\Http\Authenticator\Debug\TraceableAuthenticator(new \Symfony\Component\Security\Http\Authenticator\RememberMeAuthenticator(($container->privates['security.authenticator.remember_me_handler.admin'] ?? $container->load('getSecurity_Authenticator_RememberMeHandler_AdminService')), ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)), 'REMEMBERME', ($container->privates['logger'] ?? self::getLoggerService($container))));
    }
}
