<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZqIMbF9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZqIMbF9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZqIMbF9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZqIMbF9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZqIMbF9\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZqIMbF9',
    'container.build_id' => 'aeef6e17',
    'container.build_time' => 1740611652,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZqIMbF9');
